// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3.0
// Project name: ESP32_S3_Smartwatch

#include "ui.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_ScreenClock
lv_obj_t * ui_ScreenClock;
lv_obj_t * ui_time_label;
lv_obj_t * ui_date_label;
lv_obj_t * ui_day_label;
lv_obj_t * ui_seconds_label;

// SCREEN: ui_ScreenSteps
lv_obj_t * ui_ScreenSteps;
lv_obj_t * ui_steps_title;
lv_obj_t * ui_steps_count;
lv_obj_t * ui_steps_status;

// SCREEN: ui_ScreenSettings
lv_obj_t * ui_ScreenSettings;
lv_obj_t * ui_settings_title;
lv_obj_t * ui_brightness_label;
lv_obj_t * ui_brightness_slider;
lv_obj_t * ui_battery_label;
lv_obj_t * ui_battery_value;
lv_obj_t * ui_wifi_label;
lv_obj_t * ui_wifi_status;
lv_obj_t * ui_version_label;

// SCREEN: ui_ScreenFiles (File Browser)
lv_obj_t * ui_ScreenFiles;
lv_obj_t * ui_files_title;
lv_obj_t * ui_files_sd_status;
lv_obj_t * ui_files_list;
lv_obj_t * ui_files_info;

// SCREEN: ui_ScreenViewer (Blank screen for file viewer)
// Dit is een leeg zwart scherm dat wordt geladen wanneer de file viewer actief is.
// Hierdoor schrijft LVGL niet over de gfx tekeningen heen.
lv_obj_t * ui_ScreenViewer;

lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

/*
 * ui_ScreenViewer_screen_init
 * ---------------------------
 * Creëert een leeg zwart scherm voor de file viewer.
 * Dit scherm wordt geladen wanneer een bestand wordt bekeken,
 * zodat LVGL niet over de gfx tekeningen heen schrijft.
 */
void ui_ScreenViewer_screen_init(void)
{
    ui_ScreenViewer = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenViewer, LV_OBJ_FLAG_SCROLLABLE);
    // Achtergrond zwart maken
    lv_obj_set_style_bg_color(ui_ScreenViewer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenViewer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Geen borders of padding
    lv_obj_set_style_border_width(ui_ScreenViewer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_ScreenViewer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
}

void ui_init(void)
{
    lv_display_t * disp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(disp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_display_set_theme(disp, theme);

    ui_ScreenClock_screen_init();
    ui_ScreenSteps_screen_init();
    ui_ScreenSettings_screen_init();
    ui_ScreenFiles_screen_init();
    ui_ScreenViewer_screen_init();  // Initialiseer viewer scherm

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_scr_load(ui_ScreenClock);
}
