// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3.0
// Project name: ESP32_S3_Smartwatch

#ifndef _ESP32_S3_SMARTWATCH_UI_H
#define _ESP32_S3_SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_ScreenClock
void ui_ScreenClock_screen_init(void);
extern lv_obj_t * ui_ScreenClock;
extern lv_obj_t * ui_time_label;
extern lv_obj_t * ui_date_label;
extern lv_obj_t * ui_day_label;
extern lv_obj_t * ui_seconds_label;

// SCREEN: ui_ScreenSteps
void ui_ScreenSteps_screen_init(void);
extern lv_obj_t * ui_ScreenSteps;
extern lv_obj_t * ui_steps_title;
extern lv_obj_t * ui_steps_count;
extern lv_obj_t * ui_steps_status;

// SCREEN: ui_ScreenSettings
void ui_ScreenSettings_screen_init(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_settings_title;
extern lv_obj_t * ui_brightness_label;
extern lv_obj_t * ui_brightness_slider;
extern lv_obj_t * ui_battery_label;
extern lv_obj_t * ui_battery_value;
extern lv_obj_t * ui_wifi_label;
extern lv_obj_t * ui_wifi_status;
extern lv_obj_t * ui_version_label;

// SCREEN: ui_ScreenFiles (File Browser)
void ui_ScreenFiles_screen_init(void);
extern lv_obj_t * ui_ScreenFiles;
extern lv_obj_t * ui_files_title;
extern lv_obj_t * ui_files_sd_status;
extern lv_obj_t * ui_files_list;
extern lv_obj_t * ui_files_info;

// SCREEN: ui_ScreenViewer (Blank screen for file viewer - prevents LVGL from overwriting gfx drawings)
extern lv_obj_t * ui_ScreenViewer;

extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_relo_logo_png);    // assets/ReLo_logo.png

LV_FONT_DECLARE(ui_font_Digital72);
LV_FONT_DECLARE(ui_font_Digital48);
LV_FONT_DECLARE(ui_font_Digital96);
LV_FONT_DECLARE(ui_font_Regular24);
LV_FONT_DECLARE(ui_font_Regular18);
LV_FONT_DECLARE(ui_font_Regular14);
LV_FONT_DECLARE(ui_font_Bold24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
