// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3.0
// Project name: ESP32_S3_Smartwatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Event handlers - implement these in your main code
void ui_event_steps_count(lv_event_t * e);
void ui_event_steps_count_long_press(lv_event_t * e);
void ui_event_brightness_changed(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
