// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3.0
// Project name: ESP32_S3_Smartwatch

#include "ui_helpers.h"
#include <stdarg.h>
#include <stdio.h>

void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay, void (*target_init)(void))
{
    if(*target == NULL) {
        target_init();
    }
    lv_screen_load_anim(*target, fademode, spd, delay, false);
}

void _ui_screen_delete(lv_obj_t ** target)
{
    if(*target != NULL) {
        lv_obj_delete(*target);
        *target = NULL;
    }
}

void ui_change_screen(lv_obj_t * target, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay)
{
    lv_screen_load_anim(target, anim, time, delay, false);
}

void ui_label_set_text_fmt(lv_obj_t * label, const char * fmt, ...)
{
    char buf[128];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    lv_label_set_text(label, buf);
}
