// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3.0
// Project name: ESP32_S3_Smartwatch

#ifndef _UI_HELPERS_H
#define _UI_HELPERS_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// Helper macros for screen transitions
void _ui_screen_change(lv_obj_t ** target, lv_screen_load_anim_t fademode, int spd, int delay, void (*target_init)(void));
void _ui_screen_delete(lv_obj_t ** target);

// Helper function to change screens with animation
void ui_change_screen(lv_obj_t * target, lv_screen_load_anim_t anim, uint32_t time, uint32_t delay);

// Helper to update labels safely
void ui_label_set_text_fmt(lv_obj_t * label, const char * fmt, ...);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
